//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SING.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Button {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Button() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SING.Resource.Lang.Button", typeof(Button).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string ui_btnAll {
            get {
                return ResourceManager.GetString("ui_btnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string ui_btnBrowse {
            get {
                return ResourceManager.GetString("ui_btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string ui_btnCancle {
            get {
                return ResourceManager.GetString("ui_btnCancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        public static string ui_btnChange {
            get {
                return ResourceManager.GetString("ui_btnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换显示器 的本地化字符串。
        /// </summary>
        public static string ui_btnChangeScreen {
            get {
                return ResourceManager.GetString("ui_btnChangeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string ui_btnClear {
            get {
                return ResourceManager.GetString("ui_btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string ui_btnClose {
            get {
                return ResourceManager.GetString("ui_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string ui_btnConfirm {
            get {
                return ResourceManager.GetString("ui_btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已确认 的本地化字符串。
        /// </summary>
        public static string ui_btnConfirmed {
            get {
                return ResourceManager.GetString("ui_btnConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string ui_btnCreate {
            get {
                return ResourceManager.GetString("ui_btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string ui_btnCustom {
            get {
                return ResourceManager.GetString("ui_btnCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string ui_btnDelete {
            get {
                return ResourceManager.GetString("ui_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细信息 的本地化字符串。
        /// </summary>
        public static string ui_btnDetail {
            get {
                return ResourceManager.GetString("ui_btnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已排除 的本地化字符串。
        /// </summary>
        public static string ui_btnExcluded {
            get {
                return ResourceManager.GetString("ui_btnExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string ui_btnExit {
            get {
                return ResourceManager.GetString("ui_btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏切换 的本地化字符串。
        /// </summary>
        public static string ui_btnFullScreen {
            get {
                return ResourceManager.GetString("ui_btnFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏窗口 的本地化字符串。
        /// </summary>
        public static string ui_btnHide {
            get {
                return ResourceManager.GetString("ui_btnHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入图片 的本地化字符串。
        /// </summary>
        public static string ui_btnImportImg {
            get {
                return ResourceManager.GetString("ui_btnImportImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string ui_btnLogin {
            get {
                return ResourceManager.GetString("ui_btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string ui_btnLogout {
            get {
                return ResourceManager.GetString("ui_btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未复核 的本地化字符串。
        /// </summary>
        public static string ui_btnNoCheck {
            get {
                return ResourceManager.GetString("ui_btnNoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未推送 的本地化字符串。
        /// </summary>
        public static string ui_btnNoPush {
            get {
                return ResourceManager.GetString("ui_btnNoPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送 的本地化字符串。
        /// </summary>
        public static string ui_btnPublish {
            get {
                return ResourceManager.GetString("ui_btnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已推送 的本地化字符串。
        /// </summary>
        public static string ui_btnPush {
            get {
                return ResourceManager.GetString("ui_btnPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置选项 的本地化字符串。
        /// </summary>
        public static string ui_btnResetItem {
            get {
                return ResourceManager.GetString("ui_btnResetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string ui_btnSave {
            get {
                return ResourceManager.GetString("ui_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景图 的本地化字符串。
        /// </summary>
        public static string ui_btnScene {
            get {
                return ResourceManager.GetString("ui_btnScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string ui_btnSearch {
            get {
                return ResourceManager.GetString("ui_btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择区域 的本地化字符串。
        /// </summary>
        public static string ui_btnSelectArea {
            get {
                return ResourceManager.GetString("ui_btnSelectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择布控任务 的本地化字符串。
        /// </summary>
        public static string ui_btnSelectMonTasks {
            get {
                return ResourceManager.GetString("ui_btnSelectMonTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标库 的本地化字符串。
        /// </summary>
        public static string ui_btnSelectTarLibrary {
            get {
                return ResourceManager.GetString("ui_btnSelectTarLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7日 的本地化字符串。
        /// </summary>
        public static string ui_btnSevenDays {
            get {
                return ResourceManager.GetString("ui_btnSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本周 的本地化字符串。
        /// </summary>
        public static string ui_btnThisWeek {
            get {
                return ResourceManager.GetString("ui_btnThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string ui_btnToday {
            get {
                return ResourceManager.GetString("ui_btnToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否决 的本地化字符串。
        /// </summary>
        public static string ui_btnVeto {
            get {
                return ResourceManager.GetString("ui_btnVeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string ui_btnVideo {
            get {
                return ResourceManager.GetString("ui_btnVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置窗口布局 的本地化字符串。
        /// </summary>
        public static string ui_btnVideoGrid {
            get {
                return ResourceManager.GetString("ui_btnVideoGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开窗体列表 的本地化字符串。
        /// </summary>
        public static string ui_btnWindowList {
            get {
                return ResourceManager.GetString("ui_btnWindowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 的本地化字符串。
        /// </summary>
        public static string ui_btnYesterday {
            get {
                return ResourceManager.GetString("ui_btnYesterday", resourceCulture);
            }
        }
    }
}
