//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SING.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entity() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SING.Resource.Lang.Entity", typeof(Entity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 抓拍设备通道 的本地化字符串。
        /// </summary>
        public static string ui_fieldChannelName {
            get {
                return ResourceManager.GetString("ui_fieldChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓拍时间 的本地化字符串。
        /// </summary>
        public static string ui_fieldFcapTime {
            get {
                return ResourceManager.GetString("ui_fieldFcapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相似度 的本地化字符串。
        /// </summary>
        public static string ui_fieldFcmpSocre {
            get {
                return ResourceManager.GetString("ui_fieldFcmpSocre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string ui_fieldFobjId {
            get {
                return ResourceManager.GetString("ui_fieldFobjId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string ui_fieldFobjName {
            get {
                return ResourceManager.GetString("ui_fieldFobjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人像采集时间 的本地化字符串。
        /// </summary>
        public static string ui_fieldFtImgTime {
            get {
                return ResourceManager.GetString("ui_fieldFtImgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓拍设备区域 的本地化字符串。
        /// </summary>
        public static string ui_fieldRegionName {
            get {
                return ResourceManager.GetString("ui_fieldRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅助算法策略方式 的本地化字符串。
        /// </summary>
        public static string ui_fieldRulerName {
            get {
                return ResourceManager.GetString("ui_fieldRulerName", resourceCulture);
            }
        }
    }
}
