//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SING.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Filter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filter() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SING.Resource.Lang.Filter", typeof(Filter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 判决状态: 的本地化字符串。
        /// </summary>
        public static string ui_filterAck {
            get {
                return ResourceManager.GetString("ui_filterAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址: 的本地化字符串。
        /// </summary>
        public static string ui_filterAddress {
            get {
                return ResourceManager.GetString("ui_filterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期: 的本地化字符串。
        /// </summary>
        public static string ui_filterBirthday {
            get {
                return ResourceManager.GetString("ui_filterBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓拍结束时间: 的本地化字符串。
        /// </summary>
        public static string ui_filterCapEndDateTime {
            get {
                return ResourceManager.GetString("ui_filterCapEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓拍起始时间: 的本地化字符串。
        /// </summary>
        public static string ui_filterCapStartDateTime {
            get {
                return ResourceManager.GetString("ui_filterCapStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道: 的本地化字符串。
        /// </summary>
        public static string ui_filterChannel {
            get {
                return ResourceManager.GetString("ui_filterChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间: 的本地化字符串。
        /// </summary>
        public static string ui_filterCreateTime {
            get {
                return ResourceManager.GetString("ui_filterCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截止日期: 的本地化字符串。
        /// </summary>
        public static string ui_filterEndDate {
            get {
                return ResourceManager.GetString("ui_filterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板库: 的本地化字符串。
        /// </summary>
        public static string ui_filterFtdb {
            get {
                return ResourceManager.GetString("ui_filterFtdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证件号: 的本地化字符串。
        /// </summary>
        public static string ui_filterIdNumb {
            get {
                return ResourceManager.GetString("ui_filterIdNumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证件类型 的本地化字符串。
        /// </summary>
        public static string ui_filterIdType {
            get {
                return ResourceManager.GetString("ui_filterIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字: 的本地化字符串。
        /// </summary>
        public static string ui_filterKeyword {
            get {
                return ResourceManager.GetString("ui_filterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敏感等级: 的本地化字符串。
        /// </summary>
        public static string ui_filterLevel {
            get {
                return ResourceManager.GetString("ui_filterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名: 的本地化字符串。
        /// </summary>
        public static string ui_filterName {
            get {
                return ResourceManager.GetString("ui_filterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 民族: 的本地化字符串。
        /// </summary>
        public static string ui_filterNation {
            get {
                return ResourceManager.GetString("ui_filterNation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注: 的本地化字符串。
        /// </summary>
        public static string ui_filterNote {
            get {
                return ResourceManager.GetString("ui_filterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送状态: 的本地化字符串。
        /// </summary>
        public static string ui_filterPub {
            get {
                return ResourceManager.GetString("ui_filterPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域: 的本地化字符串。
        /// </summary>
        public static string ui_filterRegion {
            get {
                return ResourceManager.GetString("ui_filterRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分数: 的本地化字符串。
        /// </summary>
        public static string ui_filterScore {
            get {
                return ResourceManager.GetString("ui_filterScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别: 的本地化字符串。
        /// </summary>
        public static string ui_filterSex {
            get {
                return ResourceManager.GetString("ui_filterSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始日期: 的本地化字符串。
        /// </summary>
        public static string ui_filterStartDate {
            get {
                return ResourceManager.GetString("ui_filterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top: 的本地化字符串。
        /// </summary>
        public static string ui_filterTop {
            get {
                return ResourceManager.GetString("ui_filterTop", resourceCulture);
            }
        }
    }
}
