//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SING.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SING.Resource.Lang.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 深醒动态人脸识别系统 的本地化字符串。
        /// </summary>
        public static string ui_title_appName {
            get {
                return ResourceManager.GetString("ui_title_appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string ui_title_error {
            get {
                return ResourceManager.GetString("ui_title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string ui_title_info {
            get {
                return ResourceManager.GetString("ui_title_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string ui_title_warn {
            get {
                return ResourceManager.GetString("ui_title_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警管理 的本地化字符串。
        /// </summary>
        public static string ui_titleAlarm {
            get {
                return ResourceManager.GetString("ui_titleAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警记录 的本地化字符串。
        /// </summary>
        public static string ui_titleAlarmHistory {
            get {
                return ResourceManager.GetString("ui_titleAlarmHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警记录 的本地化字符串。
        /// </summary>
        public static string ui_titleAlarmHistoryAlarm {
            get {
                return ResourceManager.GetString("ui_titleAlarmHistoryAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警记录 的本地化字符串。
        /// </summary>
        public static string ui_titleAlarmHistoryAlert {
            get {
                return ResourceManager.GetString("ui_titleAlarmHistoryAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能报警 的本地化字符串。
        /// </summary>
        public static string ui_titleAlarmRealtime {
            get {
                return ResourceManager.GetString("ui_titleAlarmRealtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警输出 的本地化字符串。
        /// </summary>
        public static string ui_titleAlarmRealtimeAlarm {
            get {
                return ResourceManager.GetString("ui_titleAlarmRealtimeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警输出 的本地化字符串。
        /// </summary>
        public static string ui_titleAlarmRealtimeAlert {
            get {
                return ResourceManager.GetString("ui_titleAlarmRealtimeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能分析 的本地化字符串。
        /// </summary>
        public static string ui_titleAnalyze {
            get {
                return ResourceManager.GetString("ui_titleAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无目标分析 的本地化字符串。
        /// </summary>
        public static string ui_titleAnalyzeNoTarget {
            get {
                return ResourceManager.GetString("ui_titleAnalyzeNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有目标分析 的本地化字符串。
        /// </summary>
        public static string ui_titleAnalyzeTarget {
            get {
                return ResourceManager.GetString("ui_titleAnalyzeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨迹分析 的本地化字符串。
        /// </summary>
        public static string ui_titleAnalyzeTrack {
            get {
                return ResourceManager.GetString("ui_titleAnalyzeTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源管理 的本地化字符串。
        /// </summary>
        public static string ui_titleAsset {
            get {
                return ResourceManager.GetString("ui_titleAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道管理 的本地化字符串。
        /// </summary>
        public static string ui_titleAssetChannel {
            get {
                return ResourceManager.GetString("ui_titleAssetChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板管理 的本地化字符串。
        /// </summary>
        public static string ui_titleAssetTemplate {
            get {
                return ResourceManager.GetString("ui_titleAssetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频管理 的本地化字符串。
        /// </summary>
        public static string ui_titleAssetVideo {
            get {
                return ResourceManager.GetString("ui_titleAssetVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸比对 的本地化字符串。
        /// </summary>
        public static string ui_titleCmp {
            get {
                return ResourceManager.GetString("ui_titleCmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态比对 的本地化字符串。
        /// </summary>
        public static string ui_titleCmpStatic {
            get {
                return ResourceManager.GetString("ui_titleCmpStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态比对 的本地化字符串。
        /// </summary>
        public static string ui_titleDynamicCmp {
            get {
                return ResourceManager.GetString("ui_titleDynamicCmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N:N任务 的本地化字符串。
        /// </summary>
        public static string ui_titleNNTask {
            get {
                return ResourceManager.GetString("ui_titleNNTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史检索 的本地化字符串。
        /// </summary>
        public static string ui_titleSearch {
            get {
                return ResourceManager.GetString("ui_titleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓拍记录 的本地化字符串。
        /// </summary>
        public static string ui_titleSearchCap {
            get {
                return ResourceManager.GetString("ui_titleSearchCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比对记录 的本地化字符串。
        /// </summary>
        public static string ui_titleSearchCmp {
            get {
                return ResourceManager.GetString("ui_titleSearchCmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        public static string ui_titleSystem {
            get {
                return ResourceManager.GetString("ui_titleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统日志回收 的本地化字符串。
        /// </summary>
        public static string ui_titleSystemGC {
            get {
                return ResourceManager.GetString("ui_titleSystemGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统帮助 的本地化字符串。
        /// </summary>
        public static string ui_titleSystemHelp {
            get {
                return ResourceManager.GetString("ui_titleSystemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意事项 的本地化字符串。
        /// </summary>
        public static string ui_titleSystemNote {
            get {
                return ResourceManager.GetString("ui_titleSystemNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        public static string ui_titleSystemSetting {
            get {
                return ResourceManager.GetString("ui_titleSystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string ui_titleUser {
            get {
                return ResourceManager.GetString("ui_titleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string ui_titleUserInfo {
            get {
                return ResourceManager.GetString("ui_titleUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        public static string ui_titleUserRight {
            get {
                return ResourceManager.GetString("ui_titleUserRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string ui_titleUserRole {
            get {
                return ResourceManager.GetString("ui_titleUserRole", resourceCulture);
            }
        }
    }
}
